LEHUUQUAN/Controllers/LichchieuController.cs
using LEHUUQUAN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LEHUUQUAN.Controllers
{
    public class LichchieuController : Controller
    {
        RapchieuphimDataContext data = new RapchieuphimDataContext();
        // GET: Lichchieu
        public ActionResult Index()
        {
            var all_lich = from s in data.LichChieus select s;
            return View(all_lich);
        }
    }
}

LEHUUQUAN/Controllers/NguoiDung1Controller.cs
using LEHUUQUAN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LEHUUQUAN.Controllers
{
    public class NguoiDung1Controller : Controller
    {
        // GET: NguoiDung
        RapchieuphimDataContext data = new RapchieuphimDataContext();
        public ActionResult Index()
        {
            var all_sach = from s in data.KhachHangs select s;
            return View(all_sach);


        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["hoten"];
            var matkhau = collection["matkhau"];
            var diachi = collection["diachi"];
            var dienthoai = collection["dienthoai"];

            kh.hoten = hoten;
            kh.matkhau = matkhau;
            kh.diachi = diachi;
            kh.dienthoai = dienthoai;

            data.KhachHangs.InsertOnSubmit(kh);
            data.SubmitChanges();

            return RedirectToAction("DangNhap");


            return this.DangKy();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var dienthoai = collection["dienthoai"];
            KhachHang kh = data.KhachHangs.SingleOrDefault(n => n.dienthoai == dienthoai);
            if (kh != null)
            {
                ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                Session["TaiKhoan"] = kh;
            }
            else
            {
                ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return RedirectToAction("Index", "Rapchieuphim");
        }
        // GET: NguoiDung
       
    }
}

LEHUUQUAN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Phim", "Index", "Rapchieuphim")</li>
                    <li>@Html.ActionLink("Lịch Chiếu", "Index", "Lichchieu")</li>
                    <li>@Html.ActionLink("Giỏ Hàng", "GioHang", "Giohang")</li>
                    <li>@Html.ActionLink("Đăng Nhập", "DangNhap", "NguoiDung1")</li>
                    <li>@Html.ActionLink("Đăng Ký", "DangKy", "NguoiDung1")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>